REM Remark: SourceDataDir in options menu of the GUI, tab 'general settings'is leading for localisation of the SourceData.
REM GeoDmsRun.exe [/PProjName] [/LLogFileName] ConfigFileName ItemNames
REM [] means optional
REM Close GUI-variant(GeoDmsGui.exe) if running GeoDmsRun.exe (if this is the same)
REM Results are saved in: ../LD/%configname%/results/...
REM When running again, files are simply overwritten

REM all files must be present as generated by 2up.bat
REM to run other country replace Netherlands bij other country name see Input/administrative/Countries/Country/Name_from_utf_cor

Call path/set.bat

Call createcountry_SSP1.bat
Call createcountry_SSP2.bat
Call createcountry_SSP3.bat
Call createcountry_SSP4.bat
Call createcountry_SSP5.bat
